# Generated by Django 4.2.13 on 2025-04-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawlings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=7)),
                ('comment', models.TextField()),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
